name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Generate Snake
        run: |
          pip install requests
          python -c "
          import requests
          import base64
          
          # Get contribution data
          url = 'https://github.com/aryanul'
          response = requests.get(url)
          
          # Generate snake SVG (simplified version)
          svg_content = '''<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100" viewBox="0 0 1000 100">
            <rect width="100%" height="100%" fill="#0d1117"/>
            <text x="50%" y="50%" text-anchor="middle" fill="#ffffff" font-family="Arial" font-size="24">
              GitHub Contribution Snake
            </text>
            <text x="50%" y="80%" text-anchor="middle" fill="#7c3aed" font-family="Arial" font-size="16">
              Generated by GitHub Action
            </text>
          </svg>'''
          
          # Write to file
          with open('output/github-contribution-grid-snake.svg', 'w') as f:
              f.write(svg_content)
          "
          
      - name: Create output directory
        run: mkdir -p output
        
      - name: Generate contribution snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: aryanul
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Copy snake to output directory
        run: |
          mkdir -p output
          cp dist/github-contribution-grid-snake.svg output/
          
      - name: Push to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
