name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate contribution snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: aryanul
          svg_out_path: output/github-contribution-grid-snake.svg
          
      - name: Check if snake was generated
        run: |
          if [ -f "output/github-contribution-grid-snake.svg" ]; then
            echo "Snake generated successfully"
            ls -la output/
          else
            echo "Snake file not found"
            ls -la
          fi
          
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "Update GitHub contribution snake" || exit 0
          git push
